[[nodes]]
id = 1
raft_address = "node1:8081"
client_address = "0.0.0.0:9001"
admin_address = "0.0.0.0:9991"

[[nodes]]
id = 2
raft_address = "node2:8082"
client_address = "0.0.0.0:9002"
admin_address = "0.0.0.0:9992"

[[nodes]]
id = 3
raft_address = "node3:8083"
client_address = "0.0.0.0:9003"
admin_address = "0.0.0.0:9993"